spring:
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
path:
  temp:
    dir: /temp
vosk:
  pathLanguageModels:
    RUSSIAN: /modelsVosk/vosk-model-ru-0.42
    ENGLISH: /modelsVosk/vosk-model-en-us-0.42-gigaspeech
server:
  port: 8080
