spring:
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
path:
  to:
    dir: /temp/
vosk:
  path-model: /modelsVosk/vosk-model-ru-0.42
server:
  port: 8080
